### ISSUE TITLE
Permisje

### ISSUE THREAD

**Issue by Aides123** [EternalCodeTeam/EternalCheck#15]
Nie jest to błąd ale innej kategorii do zadania pytania nie widze.
Jakie sa permisje dla tego pluginu dla gracza i admina?

**Comment by vLuckyyy** [comment]
Hej, postaramy się wypisać wszystkie permisję wraz z nowym update.

**Comment by Aides123** [comment]
Oki dziękuje

**Comment by Osnixer** [comment]
- eternalcheck.check - uprawnienie do używania /check <start/end/ban>
- eternalcheck.check.reload - uprawnienie do przeładowania plików
- eternalcheck.check.set - uprawnienie do ustawienia miejsca sprawdzania
- eternalcheck.bypass - uprawnienie nie pozwalające sprawdzić danego użytkownika
